name 'ayte-elasticsearch-acceptance'
maintainer 'The Authors'
maintainer_email 'ops@ayte.team'
license 'MIT'
description 'Acceptance testing cookbook for ayte-elasticsearch'
version '0.1.0'
chef_version '>= 13.0'

depends 'java'
depends 'elasticsearch'
depends 'ayte-elasticsearch'
